"""Add portfolio, holdings, net_worth_snapshots

Revision ID: e0a9ce23bdcf
Revises: 9e2e664abfd3
Create Date: 2026-07-11 08:54:00.102419+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e0a9ce23bdcf"
down_revision: Union[str, None] = "9e2e664abfd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "net_worth_snapshots",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_assets", sa.DECIMAL(precision=18, scale=2), nullable=False),
        sa.Column("total_liabilities", sa.DECIMAL(precision=18, scale=2), nullable=False),
        sa.Column("net_worth", sa.DECIMAL(precision=18, scale=2), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=True),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_net_worth_snapshots_id"), "net_worth_snapshots", ["id"], unique=False)
    op.create_index(
        op.f("ix_net_worth_snapshots_snapshot_date"),
        "net_worth_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_net_worth_snapshots_user_id"), "net_worth_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "portfolios",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("target_allocation", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolios_id"), "portfolios", ["id"], unique=False)
    op.create_index(op.f("ix_portfolios_user_id"), "portfolios", ["user_id"], unique=False)
    op.create_table(
        "holdings",
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.DECIMAL(precision=18, scale=6), nullable=False),
        sa.Column("cost_basis", sa.DECIMAL(precision=18, scale=6), nullable=False),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("last_price", sa.DECIMAL(precision=18, scale=6), nullable=True),
        sa.Column("last_price_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holdings_id"), "holdings", ["id"], unique=False)
    op.create_index(op.f("ix_holdings_portfolio_id"), "holdings", ["portfolio_id"], unique=False)
    op.create_index(op.f("ix_holdings_ticker"), "holdings", ["ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holdings_ticker"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_portfolio_id"), table_name="holdings")
    op.drop_index(op.f("ix_holdings_id"), table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_portfolios_user_id"), table_name="portfolios")
    op.drop_index(op.f("ix_portfolios_id"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_net_worth_snapshots_user_id"), table_name="net_worth_snapshots")
    op.drop_index(op.f("ix_net_worth_snapshots_snapshot_date"), table_name="net_worth_snapshots")
    op.drop_index(op.f("ix_net_worth_snapshots_id"), table_name="net_worth_snapshots")
    op.drop_table("net_worth_snapshots")
    # ### end Alembic commands ###
