"""add vendor_aliases table

Revision ID: 179eadb84c99
Revises: e7ac60326872
Create Date: 2026-07-11 11:47:20.148443+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "179eadb84c99"
down_revision: Union[str, None] = "e7ac60326872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_aliases",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendor_aliases_id"), "vendor_aliases", ["id"], unique=False)
    op.create_index(
        op.f("ix_vendor_aliases_raw_name"), "vendor_aliases", ["raw_name"], unique=False
    )
    op.create_index(op.f("ix_vendor_aliases_user_id"), "vendor_aliases", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendor_aliases_user_id"), table_name="vendor_aliases")
    op.drop_index(op.f("ix_vendor_aliases_raw_name"), table_name="vendor_aliases")
    op.drop_index(op.f("ix_vendor_aliases_id"), table_name="vendor_aliases")
    op.drop_table("vendor_aliases")
    # ### end Alembic commands ###
