"""add sms_phone to users table

Revision ID: 0fcf49748e2d
Revises: 179eadb84c99
Create Date: 2026-07-11 19:33:03.450508+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0fcf49748e2d"
down_revision: Union[str, None] = "179eadb84c99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("sms_phone", sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, "users", ["sms_phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "sms_phone")
    # ### end Alembic commands ###
